library(tidyverse)
source('cleaning.R')

#copy over volumes generated by synthseg, QCed by Ana
synthseg_folder <- "/Volumes/Research/lazarm03lab/labspace/AD/camcan995/derivatives/recon/synthseg"
csv_files <- list.files(synthseg_folder, ".csv$")
file.copy(file.path(synthseg_folder, csv_files), getwd())
qc = read_csv('qc.csv')
vols = read_csv('volumes.csv')

#edit subject column to remove prefix and suffix and normalize by intracranial vol
vols <- vols %>% mutate(subject = str_remove(subject, 'sub-')) %>% 
  mutate(subject = str_remove(subject, '_T1w')) %>%
  rename(participant_id = subject) %>%
  mutate(across(c(2:ncol(vols)), .fns = ~./`total intracranial`))

#merge vols with behavioral
vols <- inner_join(vols, df_old)

#hippo
t.test(`left hippocampus` ~ scd, data = vols)
t.test(`right hippocampus` ~ scd, data=vols)
#white matter
t.test(`left cerebral white matter` ~ scd, data=vols)
t.test(`right cerebral white matter` ~ scd, data = vols)
#gray matter
t.test(`left cerebral cortex` ~ scd, data = vols)
t.test(`right cerebral cortex` ~ scd, data = vols)
